config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/strawberries', to: 'strawberries#create'
  get '/strawberries',to: 'strawberries#index'
  get '/strawberries/new',to: 'strawberries#new' , as: :strawberrie_new
  get '/strawberries/:id',to: 'strawberries#show', as: :strawberrie_show
  get '/strawberries/:id/edit',to: 'strawberries#edit', as: :strawberrie_edit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/strawberry.rb
class Strawberry < ApplicationRecord
	#validaciones a nivel de aplicacion
	validates :title, presence: true
	validates :opinion, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/strawberries_controller.rb
class StrawberriesController < ApplicationController

	def index
		@strawberries=Strawberry.all
	end

	def show
		@straw=Strawberry.find(params[:id])

	end

	def new
		@straw=Strawberry.new
	end

	def edit
		@straw=Strawberry.find(params[:id])
	end

	def create
		@straw = Strawberry.new(product_params)
		#ver por pantalla
		pp @straw

		if @straw.save
			redirect_to strawberries_path, notice: "Tu producto se ha creado correctamente"
		else
			render :new,status: :unprocessable_entity
			
		end
	end



	private

	def product_params
		params.require(:strawberry).permit(:title,:opinion)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strawberries</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div>
    <%= render 'shared/flash' %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
  <%=link_to  strawberries_path do%>
  <h1>CatFruts</h1>
  <%end%>

  <%= link_to "New", strawberrie_new_path%>

app/views/strawberries/edit.html.erb
<h1>EDITA TU STRAWBERRIE</h1>

app/views/strawberries/index.html.erb
<h1>Strawberries:</h1>


<% @strawberries.each do |strawberry| %>
	<%= link_to strawberrie_path(strawberry.id), class: 'product' do%>
	<h2> <%= strawberry.title%></h2>
	<p> <%= strawberry.opinion%></p>
	<%end%>
<% end %>

app/views/strawberries/new.html.erb
<h1>Crea un nuevo Strawberrie</h1>

<%= form_with model: @straw do |form| %>
	<% @straw.errors.full_messages.each do |error| %>
		<%= error %>
	<% end %>
<div>
	<%= form.label :'Title' %>
	<%= form.text_field :title %>

</div>
<br></br>


<div>
	<%= form.label :'Opinion' %>
	<%= form.text_area :opinion %>
</div>

<%=form.submit %>

<%end%>

app/views/strawberries/show.html.erb
<h2 class="title"><%= @straw.title %></h2>
<p><%= @straw.opinion %></p>